#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-checker-compat-qual
Version  : 2.0.0
Release  : 1
URL      : https://repo1.maven.org/maven2/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar
Source0  : https://repo1.maven.org/maven2/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar
Source1  : https://repo1.maven.org/maven2/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: mvn-checker-compat-qual-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-checker-compat-qual package.
Group: Data

%description data
data components for the mvn-checker-compat-qual package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar
/usr/share/java/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.pom
